package PRINCIPAL.POSTS;

import VARIAVEIS.*;
import METODOS.*;
import java.awt.Color;

import java.io.*;
import java.nio.file.*;
import java.util.ArrayList;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.nio.file.Files;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;

public class IfrmPost extends javax.swing.JInternalFrame {

    private static IfrmPost ifrmPost;

    private Posts post = new Posts();
    private User user = new User();
    private MEPosts mePosts = new MEPosts();
    private MEUser meUser = new MEUser();
    private String nomeFoto;

    private int idUser;
    private String tipoUser;

    private File arquivo;

    
    public static IfrmPost getInstance() {
        if (ifrmPost == null) {
            ifrmPost = new IfrmPost();
        }
        return ifrmPost;
    }

    public void abreFecha() {
        if (ifrmPost.isVisible()) {
            ifrmPost.setVisible(false);
        } else {
            ifrmPost.setVisible(true);
        }
    }
    
    public void setIdUser(int idUser){
        this.idUser = idUser;
    }

    public IfrmPost() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPostar = new javax.swing.JPanel();
        lblTextoPost = new javax.swing.JLabel();
        scrTextoPost = new javax.swing.JScrollPane();
        txtPost = new javax.swing.JTextArea();
        btnImagem = new javax.swing.JButton();
        btnPostar = new javax.swing.JButton();
        pnlDesign = new javax.swing.JPanel();
        lblImagemPost = new javax.swing.JLabel();
        scrResultPost = new javax.swing.JScrollPane();
        txtResultPost = new javax.swing.JTextArea();

        pnlPostar.setBackground(new java.awt.Color(0, 0, 0));
        pnlPostar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Post", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 0, 15), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlPostar.setForeground(new java.awt.Color(255, 255, 255));

        lblTextoPost.setBackground(new java.awt.Color(0, 0, 0));
        lblTextoPost.setForeground(new java.awt.Color(255, 255, 255));
        lblTextoPost.setText("Digite o texto do post:");

        txtPost.setColumns(20);
        txtPost.setRows(5);
        txtPost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPostKeyReleased(evt);
            }
        });
        scrTextoPost.setViewportView(txtPost);

        btnImagem.setText("Adicionar imagem");
        btnImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagemActionPerformed(evt);
            }
        });

        btnPostar.setText("Publicar");
        btnPostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPostarLayout = new javax.swing.GroupLayout(pnlPostar);
        pnlPostar.setLayout(pnlPostarLayout);
        pnlPostarLayout.setHorizontalGroup(
            pnlPostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPostarLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(lblTextoPost)
                .addGap(91, 91, 91))
            .addGroup(pnlPostarLayout.createSequentialGroup()
                .addGroup(pnlPostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPostarLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(scrTextoPost, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPostarLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnImagem))
                    .addGroup(pnlPostarLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btnPostar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPostarLayout.setVerticalGroup(
            pnlPostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPostarLayout.createSequentialGroup()
                .addComponent(lblTextoPost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrTextoPost, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnImagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btnPostar)
                .addGap(60, 60, 60))
        );

        pnlDesign.setBackground(new java.awt.Color(51, 51, 51));
        pnlDesign.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Design", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 0, 15), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlDesign.setForeground(new java.awt.Color(255, 255, 255));

        lblImagemPost.setBackground(new java.awt.Color(0, 0, 0));
        lblImagemPost.setForeground(new java.awt.Color(255, 0, 0));
        lblImagemPost.setText("Sem imagem!");

        txtResultPost.setEditable(false);
        txtResultPost.setColumns(20);
        txtResultPost.setRows(5);
        scrResultPost.setViewportView(txtResultPost);

        javax.swing.GroupLayout pnlDesignLayout = new javax.swing.GroupLayout(pnlDesign);
        pnlDesign.setLayout(pnlDesignLayout);
        pnlDesignLayout.setHorizontalGroup(
            pnlDesignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDesignLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(pnlDesignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrResultPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagemPost, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        pnlDesignLayout.setVerticalGroup(
            pnlDesignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDesignLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblImagemPost, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(scrResultPost, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPostar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDesign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPostar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlDesign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPostKeyReleased
        txtResultPost.setText(txtPost.getText());
        txtPost.setLineWrap(true);
    }//GEN-LAST:event_txtPostKeyReleased

    private void btnPostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostarActionPerformed
        setarDados();
        mePosts.inserir(post);
        ifrmPost.dispose();
        limpar();
    }//GEN-LAST:event_btnPostarActionPerformed

    private void btnImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagemActionPerformed
        JFileChooser caixaDialogo = new JFileChooser();
        int opcao = caixaDialogo.showOpenDialog(this);

        if (opcao == JFileChooser.APPROVE_OPTION) {
            arquivo = new File(caixaDialogo.getSelectedFile().getAbsolutePath());
            nomeFoto = caixaDialogo.getSelectedFile().getName();
            File destino = new File("/home/joao4774/Contrate-Aqui/Contrate Aqui/src/FOTOS/POSTS/" + nomeFoto);
            //File destino = new File("C:\\Contrate-Aqui\\Contrate Aqui\\src\\FOTOS\\POSTS\\" + nomeFoto);
            post.setImagemPost(nomeFoto);

            try {
                Files.copy(arquivo.toPath(), destino.toPath(), StandardCopyOption.REPLACE_EXISTING);
                lblImagemPost.setText("A imagem foi adicionada!");
                lblImagemPost.setForeground(Color.green);

                BufferedImage leImage = ImageIO.read(destino);
                Image redimensiona = leImage.getScaledInstance(210, 180, Image.SCALE_SMOOTH);
                BufferedImage redimensionando = new BufferedImage(210, 180, BufferedImage.TYPE_INT_RGB);
                Graphics2D g2d = redimensionando.createGraphics();
                g2d.drawImage(redimensiona, 0, 0, null);
                g2d.dispose();
                ImageIO.write(redimensionando, "jpg", destino);
            } catch (IOException err) {
                throw new RuntimeException("Erro na imagem do post: " + err);
            }
        }
    }//GEN-LAST:event_btnImagemActionPerformed
    private void setarDados() {
        post.setTextoPost(txtPost.getText());

        DateFormat formato = new SimpleDateFormat("YYYY-MM-dd HH:mm:ss");
        post.setDataPost(formato.format(new Date()));

        post.setIdUserPost(String.valueOf(idUser));

        ArrayList<User> tipo = meUser.pesquisarUser(idUser);
        for (User u : tipo) {
            post.setEmailPost(u.getEmailUser());
            tipoUser = u.getTipoUser();
        }

        switch (tipoUser) {
            case "Autônomo":
                post.setPublicoPost("Colaborador/Empresa");
                break;

            case "Colaborador":
                post.setPublicoPost("Autônomo/Empresa");
                break;

            case "Empresa":
                post.setPublicoPost("Autônomo/Colaborador/Jovem Aprendiz");
                break;

            case "Jovem Aprendiz":
                post.setPublicoPost("Empresa");
                break;
        }
    }

    private void limpar() {
        txtPost.setText("");
        lblImagemPost.setText("Sem imagem!");
        lblImagemPost.setForeground(Color.RED);
        txtResultPost.setText("");

        arquivo = null;

        post.setIdUserPost(null);
        post.setEmailPost(null);
        post.setDataPost(null);
        post.setTextoPost(null);
        post.setImagemPost(null);

        post.setFinalizadoPost(null);
        post.setPublicoPost(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImagem;
    private javax.swing.JButton btnPostar;
    private javax.swing.JLabel lblImagemPost;
    private javax.swing.JLabel lblTextoPost;
    private javax.swing.JPanel pnlDesign;
    private javax.swing.JPanel pnlPostar;
    private javax.swing.JScrollPane scrResultPost;
    private javax.swing.JScrollPane scrTextoPost;
    private javax.swing.JTextArea txtPost;
    private javax.swing.JTextArea txtResultPost;
    // End of variables declaration//GEN-END:variables
}
