package PRINCIPAL.POSTS;

import VARIAVEIS.*;
import VARIAVEIS.PERFIL.*;
import METODOS.MEPosts;
import METODOS.PERFIL.*;

import java.util.ArrayList;

public class IfrmVerPerfil extends javax.swing.JInternalFrame {

    private static IfrmVerPerfil ifrmPerfil;
    private Posts posts = new Posts();
    private User user = new User();
    private MEPosts mePosts = new MEPosts();
    private MEAutonomo meAutonomo = new MEAutonomo();
    private MEColaborador meColaborador = new MEColaborador();
    private MEEmpresa meEmpresa = new MEEmpresa();
    private MEJAprendiz meJAprendiz = new MEJAprendiz();

    private String email;
    private String tipo;
    private int id;

    public static IfrmVerPerfil getInstance() {
        if (ifrmPerfil == null) {
            ifrmPerfil = new IfrmVerPerfil();
        }
        return ifrmPerfil;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public IfrmVerPerfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblFilho = new javax.swing.JLabel();
        lblExperiencia = new javax.swing.JLabel();
        scrBio = new javax.swing.JScrollPane();
        txtBio = new javax.swing.JTextArea();
        lblTelefone = new javax.swing.JLabel();
        lblDadosProfissionais = new javax.swing.JLabel();
        lblEdita1 = new javax.swing.JLabel();
        lblEdita2 = new javax.swing.JLabel();
        lblEdita3 = new javax.swing.JLabel();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lblFoto.setBackground(new java.awt.Color(0, 0, 0));
        lblFoto.setForeground(new java.awt.Color(255, 255, 255));
        lblFoto.setText("Foto");

        lblNome.setBackground(new java.awt.Color(0, 0, 0));
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Nome");

        lblEmail.setBackground(new java.awt.Color(0, 0, 0));
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email");

        lblEndereco.setBackground(new java.awt.Color(0, 0, 0));
        lblEndereco.setForeground(new java.awt.Color(255, 255, 255));
        lblEndereco.setText("Endereço");

        lblData.setBackground(new java.awt.Color(0, 0, 0));
        lblData.setForeground(new java.awt.Color(255, 255, 255));
        lblData.setText("Data");

        lblFilho.setBackground(new java.awt.Color(0, 0, 0));
        lblFilho.setForeground(new java.awt.Color(255, 255, 255));
        lblFilho.setText("Filho");

        lblExperiencia.setBackground(new java.awt.Color(0, 0, 0));
        lblExperiencia.setForeground(new java.awt.Color(255, 255, 255));
        lblExperiencia.setText("Experiencia");

        txtBio.setColumns(20);
        txtBio.setRows(5);
        scrBio.setViewportView(txtBio);

        lblTelefone.setBackground(new java.awt.Color(0, 0, 0));
        lblTelefone.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefone.setText("Telefone");

        lblDadosProfissionais.setBackground(new java.awt.Color(0, 0, 0));
        lblDadosProfissionais.setForeground(new java.awt.Color(255, 255, 255));
        lblDadosProfissionais.setText("Dados profissionais:");

        lblEdita1.setBackground(new java.awt.Color(0, 0, 0));
        lblEdita1.setForeground(new java.awt.Color(255, 255, 255));
        lblEdita1.setText("Edita1");

        lblEdita2.setBackground(new java.awt.Color(0, 0, 0));
        lblEdita2.setForeground(new java.awt.Color(255, 255, 255));
        lblEdita2.setText("Edita2");

        lblEdita3.setBackground(new java.awt.Color(0, 0, 0));
        lblEdita3.setForeground(new java.awt.Color(255, 255, 255));
        lblEdita3.setText("Edita3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNome)
                    .addComponent(lblFoto))
                .addContainerGap(736, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(lblTelefone)
                            .addComponent(lblEndereco)
                            .addComponent(lblData)
                            .addComponent(lblFilho)
                            .addComponent(lblExperiencia)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addComponent(lblDadosProfissionais))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(109, 109, 109)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblEdita2)
                                .addComponent(lblEdita1)
                                .addComponent(lblEdita3)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(scrBio, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblFoto)
                .addGap(48, 48, 48)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTelefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFilho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExperiencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrBio, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDadosProfissionais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEdita1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEdita2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEdita3)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        setarDados();
        setarTipos();
        lblFoto.setText("");
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        lblNome.setText("");
        lblTelefone.setText("");
        lblEmail.setText("");
        lblEndereco.setText("");
        lblData.setText("");
        lblExperiencia.setText("");
        lblFilho.setText("");
        txtBio.setText("");

        lblEdita1.setText("");
        lblEdita2.setText("");
        lblEdita3.setText("");
    }//GEN-LAST:event_formInternalFrameClosed
    private void setarDados() {
        ArrayList<User> u = mePosts.verPerfil(email);
        for (User us : u) {
            tipo = us.getTipoUser();
            id = Integer.parseInt(us.getIdUser());

            lblNome.setText(us.getNomeUser());
            lblTelefone.setText(us.getTelefoneUser());
            lblEmail.setText(email);
            txtBio.setText(us.getBioUser());

            if (us.getFotoUser() != null) {
                lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTOS/PERFIL/" + us.getFotoUser())));
            } else {

                lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/Sem-foto.jpeg")));
            }

            if (tipo.equals("Empresa")) {
                lblEndereco.setText("Se localiza em: " + us.getEstadoUser() + ", "
                        + us.getCidadeUser() + ", " + us.getBairroUser());
            } else {
                lblEndereco.setText("Mora em: " + us.getEstadoUser() + ", "
                        + us.getCidadeUser() + ", " + us.getBairroUser());
                lblData.setText("Nasceu em: " + us.getDataUser());
                lblFilho.setText(us.getFilhoUser());

                if (us.getExperienciaUser() != null) {
                    lblExperiencia.setText(us.getExperienciaUser() + "anos de experiência");
                }
            }
        }
    }

    private void setarTipos() {
        switch (tipo) {
            case "Autônomo":
                ArrayList<Autonomo> au = meAutonomo.pesquisarAutonomo(id);
                for (Autonomo aut : au) {
                    lblEdita1.setText("Trabalha com: " + aut.getProfissaoAutonomo());
                    lblEdita2.setText(aut.getAvaliacaoAutonomo());

                    lblEdita3.setVisible(false);
                }
                break;

            case "Colaborador":
                ArrayList<Colaborador> co = meColaborador.pesquisarColaborador(id);
                for (Colaborador col : co) {
                    lblEdita1.setText("Trabalha com: " + col.getAreaColaborador());
                    lblEdita2.setText(col.getSituacaoColaborador());

                    lblEdita3.setVisible(false);
                }
                break;

            case "Empresa":
                ArrayList<Empresa> em = meEmpresa.pesquisarEmpresa(id);
                for (Empresa emp : em) {
                    lblEdita1.setText("Oferece empregos de: " + emp.getTrabalhoEmpresa());
                    lblEdita2.setText("Nota da empresa: " + emp.getNumAvaliacaoEmpresa());

                    if (emp.getEstagioEmpresa().equals("Sim")) {
                        lblEdita3.setText("Oferecemos estágios");
                    } else {
                        lblEdita3.setText("Não oferecemos estágios");
                    }

                    lblData.setVisible(false);
                    lblExperiencia.setVisible(false);
                    lblFilho.setVisible(false);

                }
                break;

            case "Jovem Aprendiz":
                ArrayList<JAprendiz> ja = meJAprendiz.pesquisarJAprendiz(id);
                for (JAprendiz jap : ja) {
                    lblEdita1.setText("Estuda na: " + jap.getInstituicaoAprendiz());
                    lblEdita2.setText("Cursando: " + jap.getAreaAprendiz());

                    lblEdita3.setVisible(false);
                }
                break;
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDadosProfissionais;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblEdita1;
    private javax.swing.JLabel lblEdita2;
    private javax.swing.JLabel lblEdita3;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblExperiencia;
    private javax.swing.JLabel lblFilho;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JScrollPane scrBio;
    private javax.swing.JTextArea txtBio;
    // End of variables declaration//GEN-END:variables
}
